### ISSUE TITLE
[wiki and script improvement] review the cachy repos uninstall script works

### ISSUE THREAD

**Issue by hazelshantz** [CachyOS/cachyos-repo-add-script#5]
after testing the repos, when wanting to remove them and return to vanilla arch on an existing arch installation, the script may fail and leave the repositories and keyring related packages installed, instead of having them removed. I had to remove them manually then fix the following error: 

` warning: alsa-lib: unknown key '%INSTALLED_DB%' in local database `
where alsa is just an example as it may happen with all packages of the system.
better explained here:
https://www.reddit.com/r/archlinux/comments/1bfxbtu/getting_a_warning_that_every_single_package_i/

so you may like to improve it.

best regards.

**Comment by 1Naim** [comment]
This is an added feature in our forked pacman https://github.com/CachyOS/pacman/commit/a8a7114a6ec9f9a1cab2e4b91c649142f084a74f, it seems that during repository removal this needs to be handled as well.

**Comment by hazelshantz** [comment]
good. looking forward for the improvements, that way there's no more issue trackers like others where the user had way worse issues.
partially offtopic: the cachy repos install script could also be improved, to warn that packages of the target arch system will be replaced by cachy ones, though, this is being discussed on https://github.com/CachyOS/wiki/issues/77

**Comment by ptr1337** [comment]
See step 2:
https://wiki.cachyos.org/features/optimized_repos/#uninstalling-cachyos-repositories

**Comment by hazelshantz** [comment]
sending me back to that link is the whole reason I opened this issue. 
I think @1Naim is right about reviewing the script to ensure no cachy leftovers remain on the system if user wants to remove the repos.
